function [nodalData,realSetData,elementData] = importNetworks(targetDir,networkName)
%function importNetworks(targetDir,networkName) takes a set of directories
%and network name strings (generated by the fibnet network generator) and
%imports the data.
%
% INPUT:    targetDir   : The directory to import from
%           networkName : A string matching the network to import
%
% OUTPUT:   nodalData   : All nodal coordinates {IDX X Y Z}
%           realSetData : Real values {IDX TYPE WIDTH HEIGHT WALL_TKN}
%                         TYPE = 1 : Solid rectangle
%                         TYPE = 2 : Hollow rectangle
%           elementData : All element connectivity {IDX START_NODE END_NODE MID_NODE REAL_IDX MAT_IDX}
%
% ABOUT:
% Imports the standard format FEM data generated by Kurosh's network
% generation module. The import scripts were generated by the MATLAB
% automatic function generator.
%
% TO DO:
%
%
% created: 09-07-2019
% author:  August Brandberg augustbr@kth.se
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
targetPointer = horzcat(targetDir,'\',networkName); % OBS only works on Windows, otherwise '/'

disp('-> Importing nodal data')
%nodalData = importNodalData(horzcat(targetPointer,'.xyz')); % Probably works in MATLAB, does not work in Octave
nodalData = dlmread(horzcat(targetPointer,'.xyz'));

disp('-> Importing type data')
%realSetData = importTypeData(horzcat(targetPointer,'.typ'));
realSetData = dlmread(horzcat(targetPointer,'.typ'));

disp('-> Importing element data')
%elementData = importElementData(horzcat(targetPointer,'.nod'));
elementData = dlmread(horzcat(targetPointer,'.nod'));

